[build.environment]
NODE_VERSION = "10.11.0"
YARN_VERSION = "1.10.1"
NPM_VERSION = "6.4.1"

[build]
command = "npm run build"
publish="path-to-react-app/build"
base="path-to-react-app"

[[redirects]]
from="/*"
to="/index.html"
status="200"